name: files_explore
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  android_intent_plus: ^4.0.3
  dartssh2: ^2.8.2
  dynamic_color: ^1.6.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  font_awesome_flutter: ^10.6.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  mmkv: ^1.3.1
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  riverpod_annotation: ^2.3.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3
  freezed: ^2.4.5
  custom_lint: ^0.5.6

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
