name: files_explore
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  android_package_manager: ^0.5.3
  dynamic_color: ^1.6.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  http: ^0.13.6
  json_annotation: ^4.8.1
  json_serializable: ^6.6.2
  mmkv: ^1.2.17
  path: ^1.8.2
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.1.0
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.4
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  freezed: ^2.3.4
  custom_lint: ^0.4.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
